#!/usr/bin/env python3
import json
from pathlib import Path

DATA_PATH = Path("data/ai-design-systems.json")
TABLE_PATH = Path("TABLE.md")

REQUIRED_KEYS = [
    "name",
    "org",
    "url",
    "license",
    "ai_features",
    "integrations",
    "maturity",
    "type",
    "tags",
    "evidence",
    "notes",
]


def _escape(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def main() -> None:
    entries = json.loads(DATA_PATH.read_text())

    for entry in entries:
        missing = [key for key in REQUIRED_KEYS if key not in entry]
        if missing:
            raise SystemExit(f"Missing keys {missing} in entry: {entry.get('name', 'unknown')}")
        if not isinstance(entry["tags"], list):
            raise SystemExit(f"Tags must be a list in entry: {entry.get('name', 'unknown')}")

    entries.sort(key=lambda item: item["name"].lower())

    lines = [
        "<!-- This table is generated by scripts/generate-table.py; do not edit manually. -->",
        "| Name | Org | URL | License | AI Features | Integrations | Maturity | AI-DS Type | Tags | Verification / Evidence | Notes |",
        "|------|-----|-----|---------|-------------|--------------|----------|-----------|------|----------|-------|",
    ]

    for entry in entries:
        tags = ", ".join(entry["tags"])
        row = [
            entry["name"],
            entry["org"],
            entry["url"],
            entry["license"],
            entry["ai_features"],
            entry["integrations"],
            entry["maturity"],
            entry["type"],
            tags,
            entry["evidence"],
            entry["notes"],
        ]
        lines.append("| " + " | ".join(_escape(str(value)) for value in row) + " |")

    TABLE_PATH.write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
